//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtudiantAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compte
    {
        public string cne { get; set; }
        public string cin { get; set; }
        public string mdp { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string lieu_naissance { get; set; }
        public string adresse { get; set; }
        public string code_postal { get; set; }
        public string tel { get; set; }
        public string filiere { get; set; }
        public string option_bac { get; set; }
        public Nullable<int> annee_bac { get; set; }
        public string mention_bac { get; set; }
        public Nullable<float> note_bac { get; set; }
        public string etablissement_bac { get; set; }
        public string academie_bac { get; set; }
        public string intitule_dip { get; set; }
        public Nullable<int> annee_dip { get; set; }
        public string mention_dip { get; set; }
        public Nullable<float> note_dip { get; set; }
        public string etablissement_dip { get; set; }
        public string ville_dip { get; set; }
        public Nullable<int> classement_concours { get; set; }
        public Nullable<float> note_concours { get; set; }
        public string liste_concours { get; set; }
    }
}
